[build]
  base = "frontend"
  command = "ng build --configuration production"
  publish = "www"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback (Angular routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTTPS redirects (only if you have both certifile.co.uk and www.certifile.co.uk)
# [[redirects]]
#   from = "https://certifile.co.uk/*"
#   to = "https://www.certifile.co.uk/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "http://certifile.co.uk/*"
#   to = "https://www.certifile.co.uk/:splat"
#   status = 301
#   force = true